### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by jebob**
Seeing as we did something this year.

### CODE REVIEW

**Comment by abowden1989** [comment]
LGTM if this is the correct format (as in, having the separate year at the end rather than 2017-2023)

**Review by jat45 — APPROVED** [review]
We also did some work on this in 2019 if legal want to make any further suggestions.

**Comment by jebob** [comment]
> if this is the correct format (as in, having the separate year at the end rather than 2017-2023)

This was approved by Liam

**Comment by liamcurren** [comment]
Thanks - 2017-2019, 2023 works for me.

**Comment by cariaso** [comment]
https://news.ycombinator.com/item?id=34880663
https://hynek.me/til/copyright-years/
You Can Stop Updating Copyright Attribution Years

**Pull request merged**
